name: lab4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: | 
        cd lab3 
        make

    - name: make run
      run: | 
        cd lab3
        make run | tee output.txt
  
    - name: verify
      run: 
        grep -z -E "55" lab3/output.txt
